name: Deploy site

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!docs/CONTRIBUTING.md"
      - "!docs/CUSTOMIZE.md"
      - "!docs/FAQ.md"
      - "!docs/INSTALL.md"
      - "!README.md"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!docs/CONTRIBUTING.md"
      - "!docs/CUSTOMIZE.md"
      - "!docs/FAQ.md"
      - "!docs/INSTALL.md"
      - "!README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Reconstruct CV PDF 📄
        run: |
          echo "c1271e3aec8401531ff1b7871e53919cf496106b31ae0646734df0b545939401  assets/pdf/cv_chunks/00.txt" | sha256sum --check --strict
          echo "3147c99afa4e98fd1be3a093e41b98d69480cf921b51dc04d94202704b52fcc2  assets/pdf/cv_chunks/01.txt" | sha256sum --check --strict
          echo "90aa097998297cf3b9ec6df977994217317349f2c9737c73dfdafc905557865a  assets/pdf/cv_chunks/02a.txt" | sha256sum --check --strict
          echo "21f97183450d7ec57371b46a0f1bebcde9099a4761e79400a7e966be3683239e  assets/pdf/cv_chunks/02b1.txt" | sha256sum --check --strict
          echo "9d6a6c751643f2b6311b9c05992e15842e34a149bd537f3d226f5828d8620d0c  assets/pdf/cv_chunks/02b2.txt" | sha256sum --check --strict
          echo "676bef9cab1e43c693a94bc6867236701904853d6797f393d7ab03042591b734  assets/pdf/cv_chunks/03.txt" | sha256sum --check --strict
          echo "e2449f512727e9469080eeb22a0aa8fcab6e61a6cca2c23cf9cd28fb0357a109  assets/pdf/cv_chunks/04.txt" | sha256sum --check --strict
          echo "6645748680030843b2a1ad33317ce7e29ef290c4015ed0d088848ff4ba6e1f33  assets/pdf/cv_chunks/05.txt" | sha256sum --check --strict
          echo "3e4a299cfbfee789b079b5c765336dd9127139a914916fd23c4deaef02f63395  assets/pdf/cv_chunks/06a.txt" | sha256sum --check --strict
          echo "52e5df4407e0a05536909fdbbc187b7db29cbde9e555eeb2ccc5c1b1ef573865  assets/pdf/cv_chunks/06b.txt" | sha256sum --check --strict
          echo "3d0d41e057be78872cb6759cf37eb55be2f34ab3986007e9d84cc74501d1d7f1  assets/pdf/cv_chunks/07.txt" | sha256sum --check --strict
          {
            cat assets/pdf/cv_chunks/00.txt
            cat assets/pdf/cv_chunks/01.txt
            cat assets/pdf/cv_chunks/02a.txt
            cat assets/pdf/cv_chunks/02b1.txt
            cat assets/pdf/cv_chunks/02b2.txt
            cat assets/pdf/cv_chunks/03.txt
            cat assets/pdf/cv_chunks/04.txt
            cat assets/pdf/cv_chunks/05.txt
            cat assets/pdf/cv_chunks/06a.txt
            cat assets/pdf/cv_chunks/06b.txt
            cat assets/pdf/cv_chunks/07.txt
          } | base64 --decode > assets/pdf/Maha_Sajid_CV.pdf
          echo "705a8ca83f64ff31bdef0f518332c233834f90b5a847b0eaa50122027fe0601c  assets/pdf/Maha_Sajid_CV.pdf" | sha256sum --check --strict
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Setup Node 🧰
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install JS deps 📦
        run: npm ci
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}
      - name: Install and Build 🔧
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip3 install --upgrade nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Purge unused CSS 🧹
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
